### ISSUE TITLE
Moving from shape to shape

### ISSUE THREAD

**Issue by RobinTheSprite** [RobinTheSprite/cs372-CPS#13]
We need to nail down how exactly we want to move from one shape to the next. This could be done by setting the next starting point at the end of every generate() function, or moving the current point with some sort of free function.

**Comment by jacobguenther** [comment]
Shapes draw themselves wherever they are. The current point should be the same before and after they are drawn. To move the current location use a spacer which I just implemented using translate. I need to go back to the horizontal and vertical shapes so that they reset where the current point is.

**Comment by RobinTheSprite** [comment]
Okay, I will do the same in my own classes.
