### ISSUE TITLE
Example Program

### ISSUE THREAD

**Issue by jacobguenther** [RobinTheSprite/cs372-CPS#14]

**Comment by bgklug** [comment]
I created one in the example_code branch. However I can't get the vector<unique_ptr<cps::Shape>> to work. I get 'error: no matching constructor for initialization of 'vector<unique_ptr<cps::Shape> >' '

I don't know where to go from here.

**Comment by jacobguenther** [comment]
I created another branch feature/example before. A vector of unique_ptrs can only be initialized empty because initializer lists copy the elements. So you have to use either emplace_back, or push_back on the vector after it is created, or pushShape on the compoundshape.
